version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ordersystem_web:1.0"
    ports:
      - "80:8000"
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  db:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABBASE: "OrderSystemDB"
      MYSQL_USER: "ken"
      MYSQL_PASSWORD: "0317"
      MYSQL_ROOT_PASSWORD: "0317"
    container_name: "ordersystem_db_v1.0"
    volumes:
      - /mnt/Ken/Ken/docker-compose/storage/ordersystem-data:/var/lib/mysql
    ports:
      - "33065:3306"
