version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ordersystem_web:1.0"
    ports:
      - "80:8000"
    volumes:
      - .:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  db:
    image: "sqlite3:latest"
    container_name: "ordersystem_db:1.0"
    ports:
      - "3306:3306"
