# Generated by Django 4.2.3 on 2023-08-08 18:41

import Menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLA', '經典涮肉火鍋'), ('PRE', '特級涮肉火鍋'), ('FLA', '風味涮肉火鍋'), ('VEG', '風味素食火鍋'), ('LAS', '海陸雙饗火鍋'), ('SF', '原味海鮮火鍋'), ('SD', '附餐'), ('SG', '單點')], max_length=8, verbose_name='火鍋種類')),
                ('meat', models.CharField(choices=[('GEN', '一般'), ('H', '+ 50 %'), ('D', '+ 100 %'), ('P', '豬肉'), ('B', '牛肉'), ('CHI', '雞肉'), ('NO', '不用選擇')], max_length=8, verbose_name='肉量選擇')),
                ('name', models.CharField(db_index=True, max_length=8, verbose_name='餐點名稱')),
                ('price', models.PositiveSmallIntegerField(verbose_name='餐點價格')),
                ('is_sold_out', models.BooleanField(default=False, verbose_name='餐點是否售完')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Menu.models.food_img_path, verbose_name='餐點圖片路徑')),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
    ]
